// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXo3WFkHHvTLcGSYN8t8aK7NjqjNKyBGo',
    appId: '1:95248318575:android:60fe566e0c235379',
    messagingSenderId: '95248318575',
    projectId: 'stockpathshala-cc3c6',
    databaseURL: 'https://stockpathshala-cc3c6.firebaseio.com',
    storageBucket: 'stockpathshala-cc3c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAiP3R2rNgAMn2jszjRZZOtGzuFFHrk-Y',
    appId: '1:95248318575:ios:9043687dcd64119b59cd9a',
    messagingSenderId: '95248318575',
    projectId: 'stockpathshala-cc3c6',
    databaseURL: 'https://stockpathshala-cc3c6.firebaseio.com',
    storageBucket: 'stockpathshala-cc3c6.appspot.com',
    androidClientId: '95248318575-2cmogqkiqgatomtbrt57bvv9v47icpbe.apps.googleusercontent.com',
    iosClientId: '95248318575-liei8kcs9mn6ueqqi6dcp4d39g8bbs77.apps.googleusercontent.com',
    iosBundleId: 'com.codeclinic.stockpathshala',
  );
}
